### PR TITLE
Fix viewtreeobserver

### LINKED ISSUE #70: Tracking over not initialised view
If the user starts tracking over a not initialized view, we're getting the following error

```
W: threadid=83: thread exiting with uncaught exception (group=0x41a23c98)
W: threadid=83: uncaught exception occurred
W: java.lang.IllegalStateException: This ViewTreeObserver is not alive, call getViewTreeObserver() again
W:     at android.view.ViewTreeObserver.checkIsAlive(ViewTreeObserver.java:720)
W:     at android.view.ViewTreeObserver.removeOnGlobalLayoutListener(ViewTreeObserver.java:529)
W:     at android.view.ViewTreeObserver.removeGlobalOnLayoutListener(ViewTreeObserver.java:516)
W:     at net.pubnative.library.tracking.PubnativeImpressionTracker$CheckImpressionRunnable.run(PubnativeImpressionTracker.java:91)
W:     at java.lang.Thread.run(Thread.java:841)
W: threadid=83: calling UncaughtExceptionHandler
W: java.lang.IllegalStateException: This ViewTreeObserver is not alive, call getViewTreeObserver() again
W:     at android.view.ViewTreeObserver.checkIsAlive(ViewTreeObserver.java:720)
W:     at android.view.ViewTreeObserver.removeOnGlobalLayoutListener(ViewTreeObserver.java:529)
W:     at android.view.ViewTreeObserver.removeGlobalOnLayoutListener(ViewTreeObserver.java:516)
W:     at net.pubnative.library.tracking.PubnativeImpressionTracker$CheckImpressionRunnable.run(PubnativeImpressionTracker.java:91)
W:     at java.lang.Thread.run(Thread.java:841)
```

Any type of error of this kind should be avoided.

I purpose to check if `ViewTreeObserver` is active, otherwise drop the call and warn the user.

This should also be specified in the readme file, to only call startTracking when the view is in the screen.

### PR DESCRIPTION
**Pull request by anshumansworld**
This includes, whether viewTreeObserver is alive at the time of adding/removing layout listeners.

This is meant to fix #70

### CODE REVIEW

File: library/src/main/java/net/pubnative/library/tracking/PubnativeImpressionTracker.java [hunk 1]
```diff
@@ -193,6 +193,37 @@ private void stopImpressionTracking() {
...
+                        e.printStackTrace();
+                    }
+                    if(mView.getViewTreeObserver().isAlive()) {
+                        addListeners();
+                        break;
+                    }
+                }
+            }
+        }).start();
+    }
```
Comment (cerberillo) [inline library/src/main/java/net/pubnative/library/tracking/PubnativeImpressionTracker.java]: This watch should be stopped in case of `stopTracking`

File: library/src/main/java/net/pubnative/library/tracking/PubnativeImpressionTracker.java [hunk 2]
```diff
@@ -191,6 +192,44 @@ private void stopImpressionTracking() {
...
+        if(mViewTreeObserverThread == null) {
+            mViewTreeObserverThread = new Thread(new Runnable() {
+                @Override
+                public void run() {
+                    while (true) {
+                        try {
+                            Thread.sleep(VISIBILITY_CHECK_INTERVAL);
+                        } catch (InterruptedException e) {
+                            e.printStackTrace();
+                        }
```
Comment (cerberillo) [inline library/src/main/java/net/pubnative/library/tracking/PubnativeImpressionTracker.java]: Do tis check AFTER and only if is not alive please, and remove the e.printStackTrace, you should log an error and that's all

File: library/src/main/java/net/pubnative/library/tracking/PubnativeImpressionTracker.java [hunk 3]
```diff
@@ -142,12 +122,20 @@ public void stopTracking() {
...
      */
-    public void startTracking() {
+    public void startTracking(View view, Listener listener) {
 
         Log.v(TAG, "startTracking");
-        // Impression tracking
-        mViewTreeObserver.addOnGlobalLayoutListener(onGlobalLayoutListener);
-        mViewTreeObserver.addOnScrollChangedListener(onScrollChangedListener);
+        if (listener == null) {
+            Log.e(TAG, "Error: No listener for callbacks, dropping call");
```
Comment (anshumansworld) [inline library/src/main/java/net/pubnative/library/tracking/PubnativeImpressionTracker.java]: It should be warning only. Developer can use it without listeners so I think dropping it here would not be good.
